.github/PULL_REQUEST_TEMPLATE/adr_pr_template.md, .github/PULL_REQUEST_TEMPLATE/research_pr_template.md
When we merge these templates to `main` we'll be able to see if they are exposed in the PR ui. I don't think they will be.
Source https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
=> add two test pr templates

decision-record/DR002-no-charges-for-lower-volume-services.md
In more recent team discussions following some cost modelling, our tech costs would be much higher than forecast if higher volume services started to use GOV.UK Forms. This revision would allow us to charge for these forms in the future if that meant the majority of forms can be created and run for free.
=> Revision: give us option to charge high vol services

ADR/ADR011-deployment-pipelines.md
ADR for the use of CodePipeline and CodeBuild for managing deployments to the new GOV.UK Forms AWS Environments.
=> Add ADR for use of AWS CodePipeline

ADR/ADR012-use-rails-api-for-api.md
---
[Preview ADR](https://github.com/alphagov/forms/blob/adr-switch-grape-to-rails-api/ADR/ADR012-use-rails-api-for-api.md)
Switching forms-api from ruby-grape to rails-api. All the developers on the team agree that this is a good first step to
take where we only use one framework that we are all familiar with or can follow the various conventions and patterns. 
The idea is that we would still keep to our 3 separate micro services and see whether this enables us to feel …
=> ADR012 - Use rails-api for api

ADR/ADR013-use-paper-trail-gem-for-auditing-and-record-backups.md
[ADR for adding PaperTrail ](https://github.com/alphagov/forms/blob/adr-paper-trail-for-auditting/ADR/ADR013-use-paper-trail-gem-for-auditing-and-record-backups.md)
PR to add PaperTrail to forms-api: https://github.com/alphagov/forms-api/pull/212
=> ADR: Adding PaperTrail to forms-api for auditing/restoration of our ActiveRecords.

diagrams/sequence-diagrams/changing-a-form.md, diagrams/sequence-diagrams/publishing-a-form.md
Updates the sequence diagrams to include the changes from PR alphagov/forms-admin#331, which removes the `/forms/{form-id}/live-confirmation` endpoint and the redirect to that page in favour of immediately rendering the confirmation page.
Take a look at the revised sequence diagram and check they make sense to you and match the changes in the PR above.
Anyone except me.
=> Update sequence diagrams for forms-admin PR #331

ADR/ADR017-use-paper-trail-for-draft-live-or-some-other-solution.md
ADR to record our decision not to use paper trail for draft/live but ended up decided on implementing our own simplified implementation. Expect another ADR that will cover our own implementation.
=> ADR for rejecting paper_trail-association_tracking and active_snapshot

ADR/ADR018-use-govuk-organisation-api.md
Document the decision to use the GOV.UK organisation API. See [ADR018](./ADR/ADR018-use-govuk-organisation-api.md) and ticket https://trello.com/c/kKEiA0Bq for details.
- Product manager
- Tech architect
- Developers
- Content designer
- Tech writer
=> Add ADR for using GOV.UK Organisation API

ADR/ADR020-e2e-tests-get-own-repo.md
Created an ADR discussing separating the e2e tests from `forms-deploy` and moving them into a new repo called `forms-e2e-tests` 
Anyone who's interested in the e2e tests!
=> Add ADR for e2e tests moving to their own repo

diagrams/sequence-diagrams/creating-a-form.md
Trello card: https://trello.com/c/pt9lphfe
We've changed our system to use organisation ID instead of organisation slug when communicating between the API and the admin app (see alphagov/forms-api#295). This commit updates our documentation to match.
Anyone
=> Replace org with organisation_id

ADR/ADR022-use-postgresql-for-form-creation-in-form-admin.md
Credit for a large portion of the Context and Strategy sections of this ADR to @thomasiles - thank you!
[Rendered view](https://github.com/alphagov/forms/blob/add-adr-22/ADR/ADR022-use-postgresql-for-form-creation-in-form-admin.md)
[Trello](https://trello.com/c/iHPh87YA/1031-rfc-for-switching-to-postgresql-in-forms-admin-instead-of-redis)
---
Adds an ADR for forms-admin data persistence.
Spike from Al
For example:
1. Syntactic: …
=> Add ADR 22: Store forms in forms-admin before sending to forms-api

diagrams/sequence-diagrams/authentication.md
Trello: https://trello.com/c/PET8LyHH/1120-update-authentication-sequence-diagrams
I've made a few changes to this diagram to try and make it clearer what's happening. I'm happy to revert/change any of them if it's not helping.
In this PR, I've:
- Added the missing redirect to forms admin/auth/auth0.
- Split Auth0 into two actors to reflect the different roles it's playing in our system.
Originally this was to show the difference between our login session and the [auth0 session](https://auth0.com/docs/manage-users/sessions/session-layers).
[It turns out this doesn't need to be documented
yet](https://trello.com/c/rmk3P0kO/1299-fix-auth0-single-sign-on), but I think it still might be useful. It would be good to compare with the google workspace diagram.
It could be that auth0 is outside …
=> Update auth diagram with session timeout

ADR/ADR023-use-uid-in-urls.md
Rendered view https://github.com/alphagov/forms/blob/adr-reaplacing-form-ids-in-urls/ADR/ADR023-use-uid-in-urls.md
This ADR covers the changes that [this spike](https://trello.com/c/BruuEN5Z/1225-spike-change-ids-in-urls-of-forms-to-not-be-the-primary-key) has led to. 
The idea is we don't want to expose our database IDs in our URLs, and in order to do this we need to use something other than our IDs to retrieve our forms from the API.
=> ADR for replacing form-id in urls

design/features/previewing-a-question/version-1.md
I've added a link to a document of content for previewing a question for each different answer type. This is just a temporary measure for now - until the content is updated in the prototype when we can document it properly.
1. check the link works. 
2. check Hannah hasn't made any typos or errors. 
3. tell Hannah if you think this is a terrible thing to do. 
Anyone. Only needs one review.
=> Add link to drafted content for question previews

ADR/ADR024-store-allowed-domain-list-as-file-in-forms-deploy.md
Trello ticket: https://trello.com/c/7Wfx1tI5/1255-spike-how-to-support-allow-deny-lists-from-a-shared-source
For example:
=> Add ADR Store allowed email domain list as file in forms deploy

ADR/ADR013-use-paper-trail-gem-for-auditing-and-record-backups.md, ADR/ADR025-remove-papertrail.md
---
Let's remove Papertrail. We added it a year ago and are not using it for versioning. We can add it back in when we want to do versioning and are using it for that purpose.
For example:
@alphagov/forms-devs
=> Add ADR to remove Papertrail

ADR/ADR027-scheduled-smoke-tests.md
ADR for how we'll run scheduled smoke tests.
Please see the Trello Ticket for the spike into running scheduled smoke tests for more information including working infra and capybara code: https://trello.com/c/oRlozBpd/1393-spike-smoke-tests
=> Add ADR For Scheduled Smoke Tests

diagrams/sequence-diagrams/authentication.md
Updates to the authentication sequence diagram, including adding a conditional for cabinet office email domains using Google Workspace integration, and showing forms-admin enforcing that super-admins must use this integration to authenticate.
Anyone in the forms-team, @james-sheppard-gov-uk should definitely double check this!
=> Update authentication sequence diagram with Google Workspace integration

research/2023-09-26-Form_Completers_Accessibility.md
- [ x] If you are proposing a new decision record document, used the right template for that
- [ x] Set yourself as the Assignee
- [ x] Tag anyone you would like to review, or @forms-design or @forms-devs
- [x ] Fill in the template below
---
Corrected the three URLs at the end of the documentation for this round of research.
Please check the changed URLs link to the documents for the correct round of research.
Any Forms team colleagues.
=> Corrected errors in URLs in user research documentation

.github/DISCUSSION_TEMPLATE/rfcs.yml
---
We've decided to make better use of GitHub's Discussion feature and also to start making RFCs. This adds a template for us to make RFCs in GitHub Discussions/
Spelling, grammar, syntax against https://docs.github.com/en/discussions/managing-discussions-for-your-community/syntax-for-discussion-category-forms 
@alphagov/forms-devs
=> Add GitHub discussion template for RFCs

ADR/ADR034-api-v2-for-forms.md
[Rendered view](https://github.com/alphagov/forms/blob/ldeb-adr034-api-v2-for-forms/ADR/ADR034-api-v2-for-forms.md)
---
This commit records our decision to make a new simpler API for forms.
It also includes a copy of the RFC text that was originally shared at https://docs.google.com/document/d/1lnnrtsD_TW6NSiHmmOVWEFofYBKrAg98WDILDaKRprI/view.
For example:
1. Syntactic: Spelling, …
=> Add ADR034: API v2 for Forms

ADR/ADR033-offer-amazon-s3-form-submissions.md, ADR/ADR035-offer-amazon-s3-form-submissions.md
[Rendered view](https://github.com/alphagov/forms/blob/adr-use-amazon-s3-for-submissions/ADR/ADR035-offer-amazon-s3-form-submissions.md)
---
A new ADR to allow form submissions to be sent to Amazon S3.
Anyone, but in particular those who worked on the Amazon S3 spike.
=> Add ADR035: offer Amazon S3 for form submissions

LICENCE, README.md
Adding a missing LICENSE file. Also add link to the Open Government License.
Fixes https://github.com/alphagov/forms/issues/182
=> Add licenses

ADR/ADR036-automate-patch-version-bumps.md
---
We have discussed this during Tech Weekly: we're struggling to keep on top of Dependabot updates and we'd like to make it easier for ourselves, particularly for whoever is on support.
This proposes automating patch version bumps
- Is there anything else we should be worried about?
- Do you agree with the changes?
- Are there any worries when it comes to how we might implement this?
=> Add ADR036 to automate patch version bumps

ADR/ADR041-grant-review-apps-workflow-pull-request-write-access.md
---
Proposes granting one workflow in `forms-admin` write access to pull requests.
Copy review.
Can you think of any other vulnerabilities doing so might expose? Do we have mitigations for those?
=> ADR041: Grant review apps workflow pull request write access

diagrams/sequence-diagrams/file-upload.md
Update the file upload sequence diagram.
I've separated it out into a few sub-diagrams for:
1. the user completing a file upload question
2. the user submitting the form
3. the job to send submissions
4. the job to handle bounces/complaints
Trello card: https://trello.com/c/iZiyEO33/2198-update-sequence-diagram-for-file-upload
=> Update file upload sequence diagram

diagrams/class-diagrams/README.md, diagrams/class-diagrams/admin.md, diagrams/class-diagrams/api.md, diagrams/class-diagrams/runner.md
These diagrams are not ERDs but in fact Class Diagrams. They also needed some useful context and instructions on how to update them.
Trello https://trello.com/c/ukndHQIK/2301-create-uml-and-sequence-diagrams-for-creating-welsh-forms
---
For example:
Describe who can review the changes. Or more …
=> Update and correct ERD to Class Diagrams

research/2024-10-24_Branching_round_1.md
---
New page for branching round 1 research
Anyone on feature team 2 who was there for the research.
=> Branching round 1 interviews and usability testing oct 24

README.md
---
This will aid in deep linking to the list of our repositories.
Example: [https://github.com/alphagov/forms#our-repositories](https://github.com/alphagov/forms/tree/ldeb-add-readme-repositories#our-repositories)
For example:
Anyone!
=> Add heading to README for repositories
