alphagov/forms

decision-record/DR004-our-own-designer.md
These aren't set in stone, and are rough guides for our team. They're probably better discussed internally
=> Revision: remove goals + dates from public repo

research/EPIC B MANAGING TWO VERSIONS OF THE SAME FORM.md
Hi all, see the key findings for Epic B (managing two versions of the same form)
=> Create EPIC B MANAGING TWO VERSIONS OF THE SAME FORM.md

research/EPIC-6-HOW TO HELP USERS WHEN THEY CREATE BAD FORMS.md.md
Hi all, please see the key insights from Epic 6
=> Create EPIC-6-HOW TO HELP USERS WHEN THEY CREATE BAD FORMS.md

ADR/ADR009-replatforming-to-ECS.md
Add an ADR stating the intention to move GOV.UK Forms to AWS ECS Fargate.
=> Replatforming ADR

README.md
Add a link to the private wiki
=> Updated README.md with a link to the private wiki

diagrams/sequence-diagrams/changing-a-form.md, diagrams/sequence-diagrams/publishing-a-form.md
Updating these two diagrams in prep for when we have draft/live forms
[Change a live form diagram](https://github.com/alphagov/forms/blob/436544ff16ed0df21d39ab3bd72018aaeabc295e/diagrams/sequence-diagrams/changing-a-form.md)
[Publishing a form diagram](https://github.com/alphagov/forms/blob/436544ff16ed0df21d39ab3bd72018aaeabc295e/diagrams/sequence-diagrams/publishing-a-form.md)
=> Update making live sequence diagrams

ADR/ADR014-add-conditions-to-pages.md
https://trello.com/c/P93odeqZ/508-spike-how-to-store-simple-routing-in-the-api
This ADR explains the reason for the introduction of the conditions table as the method for storing conditions for the simple routing work.
Check the ADR and suggest any changes
For example:
Anyone who's interested in the way we store conditions in the db
=> Add ADR for introducing Conditions table

ADR/ADR003-use-govuk-signon.md, ADR/ADR013-idp-authentication.md, ADR/ADR014-idp-authentication.md
---
I've created a new ADR to explain the move away from using GOV.UK Signon for authentication and authorisation.
Do you agree with the ADR? Does it explain the decision well?
@alphagov/forms-devs
=> New ADR for Identity Provider Authentication and implementing authorisation

design/features/feature-template.md, design/prototype-version-1/prototype-tested.md, design/prototype-version-2/page-detail/name-your-form.md
---
Updated version 1 documentation to include overall analysis from research that we considered and the ideas that we felt like we wanted to try or test going into version 2. 
This should not replace the research documentation/Mural, but links to this at the end. There is a bit of duplication between this write up and the Mural board where comments have been copied across and quotes have been linked to pain points or ideas we tried.
1. Are there any design decisions or changes we made that are missed for this version?
2. Are there larger “Ideas” or clear “Next steps” that have been missed? These should differ to the “Actions” that were taken as part of GitHub issues that had been created.
3. Spelling, grammar, etc.
Anyone can review.
=> V1: Design update 200223

diagrams/sequence-diagrams/filling-in-a-form.md
=> Add documentation around what we store in form-runners Redis and Session management

ADR/ADR002-use-govuk-notify.md, ADR/ADR017-use-amazon-ses.md, ADR/ADR018-use-amazon-ses.md
Discuss the problems here, and we'll add them to this ADR, and make a new ADR with our decision
=> Supersede Notify ADR

ADR/ADR002-use-govuk-notify.md, ADR/ADR019-use-amazon-ses.md
There was already an ADR018, so renamed to ADR019
Check that there aren't any ADR id clashes
Anyone
=> Adr id clash

design/features/routing/README.md, design/features/routing/version-1.md
Have made some small changes to wording for readability and house style. 
I have a few queries/comments but didn't want to put these within the text itself, so I'll try adding these as 'suggestions' once I've opened a PR request. Not sure if this is the best/only way to do this? Would be good to discuss for future reference.
---
=> Update version-1.md - minor edits

ADR/ADR021-use-auth0.md
---
Created new ADR for using Auth0.
1. Semantic: Do you agree with the ADR?
Anyone can review.
=> Create ADR021: Use Auth0

design/features/routing/version-2.md
---
Added the documentation for version 2 of the routing work done.
For example:
3. Are you happy with the captioning and alt text added to the images?
Anyone can review
=> 2023 08 22 v2 routing updates

ADR/ADRXXX-architecture-decision-record-template.md
---
The ADR template wasn't clear about which Status to use.
Do you agree with the updated template guidance?
Anyone who works with ADRs.
=> New ADR Status should be either "Accepted" or "Rejected"

diagrams/sequence-diagrams/creating-a-form.md
Update routes for "Edit question" pages
=> Minor updates to sequence diagrams

design/features/detailed-guidance/version-1.md
Just made a few minor tweaks for readability
(Had to create a new branch for this as @christophercameron-ixd had committed the file since I started editing earlier today)
---
For example:
that can't review, because they worked on …
=> Update version-1.md - tweaked content

design/features/detailed-guidance/README.md, design/features/detailed-guidance/version-1.md
---
Added outline for the detailed guidance feature.
Created a write up of version 1, including the decision to build and test a prototype. 
1. Do you agree with the changes?
2. Are there any key decisions that have been missed?
3. Syntactic: Spelling, grammar, etc.
Anyone can review
=> 2023 10 03 feature detailed guidance

design/features/form-metrics/README.md
A few tiny tweaks for readability/style
---
Made a few tiny tweaks for readability/consistency with house style
Do you agree with the changes?
=> Update README.md - tiny tweaks

design/features/form-metrics/version-1.md
Have made a few style tweaks and amended a couple of typos
Check you agree with the changes.
=> Update version-1.md - minor style tweaks

design/features/form-metrics/README.md, design/features/form-metrics/version-1.md
---
Added documentation of design work and agreed MVP for the new form metrics we are including in the forms platform.
1. Do you agree with the write up?
2. Are there any key decisions or agreements we made that have been misinterpreted or missed?
3. Spelling, grammar, etc.
Anyone in the team can review.
=> 2023 10 18 feature metrics for form creators

design/features/confirmation-email-for-form-fillers/README.md, design/features/confirmation-email-for-form-fillers/version-1.md
---
Added documentation of design work and agreed MVP for the new “confirm that a forms been submitted” email journey.  
1. Do you agree with the write up?
2. Are there any key decisions or agreements we made that have been misinterpreted or missed?
3. Spelling, grammar, etc.
Anyone in the team can review.
=> 2023 11 06 confirm that a forms been submitted

README.md
Made this more representative of what we actually have in this repo and included links to al the folders that have stuff in them.
Just check it looks ok and I've not missed any typos. 
Anyone can review this. Only needs one review.
=> Update README.md to make it more helpful and accurate

README.md
- [n/a] If you are proposing a new decision record document, used the right template for that
---
This PR adds links to our repos to the README. I suspect a lot of people will find this repo looking for our code (it's the top Google result for 'gov.uk forms github'), but there's currently no obvious way to get to our code repos from here.
You'll probably want to review on the following basis:
1. Do you agree with the changes?
2. Have I missed any of our public repos?
3. Have I described our repos properly?
1. Spelling, grammar, etc. 
Anyone apart from @DavidBiddle
=> Update README.md with links to our repos

design/README.md
- Added some positive contractions etc.
- Split a few sentences up to make them shorter
- Added a definition of 'early access'
---
=> Update README.md - minor tweaks for readability and house style

design/features/README.md
Made some small tweaks to shorten sentences etc.
=> Update README.md - small tweaks for readability

diagrams/form-states-and-events.md
https://github.com/alphagov/forms/blob/state-machine-graph/diagrams/form-states-and-events.md how forms states and events work in the current state with a diagram of where we would like to get to when adding archive state
---
For example:
Describe who can review the changes. Or more importantly, list the …
=> Add form state and events diagram

ADR/ADR025-use-aasm-to-manage-form-state.md
=> ADR - Forms states and using AASM for state machine

research/YYYY-MM-DD-template2.md
- [ x] If you are proposing a new decision record document, used the right template for that
- [ x] Set yourself as the Assignee
- [ x] Tag anyone you would like to review, or @forms-design or @forms-devs
- [ x] Fill in the template below
---
Added new template for user research documentation with additional information to include in these documents.
Check this covers everything that is useful for these documents, and nothing that is not useful.
@christophercameron-ixd
=> Created updated template for user research documentation

design/service-maps.md
=> Update content on the service-maps page

diagrams/sequence-diagrams/README.md
---
I've updated the architecture diagram that gives context to the sequence diagram to include Google Workspace, GOV.UK, and a couple of other minor improvements.
Does the diagram make sense? Is it accurate?
Anyone.
=> added Google Workspace and Pay to diagram

ADR/ADR028-use-notify-for-users.md
https://github.com/alphagov/forms/blob/add-adr-29/ADR/ADR028-use-notify-for-users.md
---
For example:
=> ADR029 specify where we use Notify

ADR/ADR028-use-shield-advanced.md, ADR/ADR029-use-shield-advanced.md
---
Add a new ADR capturing the context, decision, and pros/cons of using AWS Shield Advanced in our infrastructure.
**I've written a sparse ADR because I'm conscious this is a security-related decision on a public-facing repo.**
If we feel it's sensible and secure for me to go into further detail about consequences and/or implementation I'm happy to do so. 
1. Semantic: Do you agree with the changes? What's the balance …
=> ADR 028 for using Shield Advanced

ADR/ADR031-use-pagerduty.md, ADR/ADR032-use-statuspage.md
---
We want to document that we use, and why we use, StatusPage and PagerDuty. The reasoning is simple: because that's convention in GDS.
1. Copy review
=> ADRs for StatusPage and PagerDuty

ADR/ADR030-use-aws-lambda-to-run-glue-code.md
---
We have begun to use AWS Lambda for running glue code. This ADR documents how we arrived at that decision.
1. Copy review
2. Do we agree that this should be the path?
=> Add ADR030: use of Lambda

ADR/ADR033-swapping-jest-vitest.md
---
This is a retroactive record of this [PR](https://github.com/alphagov/forms-admin/pull/1209) and we should have recorded a change in testing framework.
For example:
* @DavidBiddle 
* @thomasiles
=> Add ADR 33 swapping Jest for Vitest

design/prototype-version-7/README.MD, design/prototype-version-7/task-list/README.md
=> Update README.MD for prototype version 7 documentation 

research/2022-08-15_Task_list_and_steps_to_make_form_live.md
---
Noticed that the “Supporting Evidence” links were all going to the wrong sprint documents. These have been updated to be linked to the correct things now. Slight alteration to the link content too to clarify what the link is for. 
Make sure the links work, and that you agree they go to the correct places. Sprint 9 - usability testing of task list.
=> Updated research links to Sprint 9 drive, mural and playback slides

design/prototype-version-3/README.md
Found a broken link from prototype-version-3 README.md file trying to go to the user research for the relevant round. 
- Updated the link text to match the UR write up heading
- Updated the link to go to the correct .md file
Make sure the link works and you agree with the content used as link text.
=> 2024 11 19 fix v3 research link

research/2024-06-18-concept_testing_add_another_answer.md
---
New research update: add another answer concept testing
1. Do you think it makes sense?
2. Spelling, grammar, etc.
Anyone.
=> Add another answer research 2024

diagrams/sequence-diagrams/file-upload.md
---
Added a new sequence diagram to explain how we think file upload will work.
Check that the sequence diagram makes sense and suggest improvements. Remember that the diagram will continue to be updated as we implement file upload and we learn more.
Anyone, but preferably those listed as "Reviewers"
=> Add file upload sequence diagram

diagrams/sequence-diagrams/file-upload.md
---
I've added an architecture diagram at the top of the page to help with the context of the sequence diagrams.
Is the architecture diagram accurate? Remember that this is likely to change along with the sequence diagrams as the file upload feature is developed.
Feature team 1 technical team.
=> Add architecture diagram

ADR/ADR039-add-aurora-for-runner.md
=> Additional Aurora cluster

ADR/ADR040-make-container-image-tags-mutable.md
---
We need to enable tag mutability in ECR for review apps to work.
Copy review. Do you agree? Not agree? Do I need to add anything else?
=> ADR040: Make container image tags mutable

ADR/ADR040-make-container-image-tags-mutable.md
=> Accept ADR040

ADR/ADR041-use-activerecord-encryption.md
=> Add ADR for ActiveRecord Encryption
